version: '3.8'

services:
  # Laravel Application
  app:
    build: .
    container_name: voanhphung-portfolio
    restart: unless-stopped
    ports:
      - "80:80"
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
      - APP_URL=http://localhost
      - DB_CONNECTION=sqlite
      - DB_DATABASE=/var/www/html/database/database.sqlite
    volumes:
      - ./storage/app/public:/var/www/html/public/storage
      - ./database/database.sqlite:/var/www/html/database/database.sqlite
    depends_on:
      - db
    networks:
      - portfolio-network

  # SQLite Database (hoặc MySQL nếu cần)
  db:
    image: alpine:latest
    container_name: portfolio-db
    restart: unless-stopped
    volumes:
      - ./database:/database
    command: >
      sh -c "
        apk add --no-cache sqlite &&
        sqlite3 /database/database.sqlite 'CREATE TABLE IF NOT EXISTS migrations (id INTEGER PRIMARY KEY, migration TEXT, batch INTEGER);' &&
        tail -f /dev/null
      "
    networks:
      - portfolio-network

  # Nginx Reverse Proxy (optional)
  nginx:
    image: nginx:alpine
    container_name: portfolio-nginx
    restart: unless-stopped
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./docker/nginx-proxy.conf:/etc/nginx/nginx.conf
      - ./docker/ssl:/etc/nginx/ssl
    depends_on:
      - app
    networks:
      - portfolio-network

networks:
  portfolio-network:
    driver: bridge

volumes:
  database-data: 